# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: jenkins-master
  Image: "quay.io/deis/jenkins-master"
  ImageTag: "canary"
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
# AdminPassword: <defaults to random>
  Cpu: "200m"
  Memory: "256Mi"
# Set min/max heap here if needed with:
# JavaOpts: "-Xms512m -Xmx512m"
  ServicePort: 8080
# For minikube, set this to NodePort, elsewhere use LoadBalancer
# Use ClusterIP if your setup includes ingress controller
  ServiceType: LoadBalancer
# Used to create Ingress record (should used with ServiceType: ClusterIP)
# HostName: jenkins.cluster.local
# NodePort: <to set explicitly, choose port between 30000-32767
  ContainerPort: 8080
  SlaveListener:
    EnableDedicatedLoadBalancer: false
    Port: 50000
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
# List of groovy init scripts to be executed during Jenkins master start
  InitScripts:
#  - |
#    print 'adding global pipeline libraries, register properties, bootstrap jobs...'
  CustomConfigMap: false
  # Tie jenkins to a specific node:
  # NodeSelector:
  #   specificnode: "true"

  Ingress:
    Annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    TLS:
      Enabled: false
      # Cert: "TODO: Add base64-encoded certificate"
      # Key: "TODO: Add base64-encoded key"
  JenkinsHome:
    HostPath: /var/jenkins_home
    MountPath: /var/jenkins_home

Agent:
  Image: quay.io/deis/jenkins-node
  ImageTag: "v0.3.0"
  Cpu: "200m"
  Memory: "256Mi"

Persistence:
  Enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # ExistingClaim:

  ## If defined, volume.beta.kubernetes.io/storage-class: <StorageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # StorageClass:
  AccessMode: ReadWriteOnce
  Size: 8Gi
  Volumes:
#  - name: nothing
#    emptyDir: {}
  Mounts:
#  - mountPath: /var/nothing
#    name: nothing
#    readOnly: true
