{{- if .Values.Master.Ingress.TLS.Enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-cert
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ .Values.Master.Ingress.TLS.Cert }}
  tls.key: {{ .Values.Master.Ingress.TLS.Key }}
{{- end }}
