{{- if .Values.Master.SlaveListener.EnableDedicatedLoadBalancer }}
apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" . }}-jnlp
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  ports:
    - port: {{.Values.Master.SlaveListener.Port}}
      targetPort: {{.Values.Master.SlaveListener.Port}}
      name: slavelistener
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
  type: LoadBalancer
  {{if eq .Values.Master.ServiceType "LoadBalancer"}}
  loadBalancerSourceRanges: {{.Values.Master.LoadBalancerSourceRanges}}
  {{end}}
{{- end }}
